######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 24 19:07:00 2014
######################################################################

TEMPLATE = app
TARGET = cpp-example
DEPENDPATH += .
INCLUDEPATH += .

# Input
# HEADERS += qt_exports.h
SOURCES += cpp-example.cpp
