######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 6 15:55:08 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += bsort.cpp
