
if(!window.FT){window.FT={};}
if(!FT.ads){FT.ads={};};
(function(win,doc,FT,undefined){"use strict";if(!String.prototype.trim){String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,'');};}
if(!Array.prototype.indexOf){Array.prototype.indexOf=function(searchElement,fromIndex){if(this===null){throw new TypeError();}
var t=Object(this);var len=t.length>>>0;if(len===0){return-1;}
var n=0;if(arguments.length>1){n=Number(arguments[1]);if(n!=n){n=0;}else if(n!==0&&n!=Infinity&&n!=-Infinity){n=(n>0||-1)*Math.floor(Math.abs(n));}}
if(n>=len){return-1;}
var k=n>=0?n:Math.max(len-Math.abs(n),0);for(;k<len;k++){if(k in t&&t[k]===searchElement){return k;}}
return-1;};}
FT=FT||{};FT._ads=FT._ads||{};FT._ads.utils=FT._ads.utils||{};var utils={};function is(object){var type=Object.prototype.toString.call(object).match(/^\[object\s(.*)\]$/)[1];if(object===null){return"Null";}else if(object===undefined){return"Undefined";}else{return type;}}
function createIsTest(className){return function(obj){return is(obj)===className;};}
function curryIsMethods(obj,classNames){classNames=classNames||["Array","Object","String","Function","Storage"];while(!!classNames.length){var className=classNames.pop();obj['is'+className]=createIsTest(className);}
return obj;}
utils=curryIsMethods(utils);utils.isWindow=function(obj){return obj&&obj!==null&&obj===window;};utils.isPlainObject=function(obj){var obj_hop=Object.prototype.hasOwnProperty;if(!obj||!utils.isObject(obj)||obj.nodeType||utils.isWindow(obj)){return false;}
try{if(obj.constructor&&!obj_hop.call(obj,"constructor")&&!obj_hop.call(obj.constructor.prototype,"isPrototypeOf")){return false;}}catch(e){return false;}
var key;for(key in obj){}
return key===undefined||obj_hop.call(obj,key);};utils.isNonEmptyString=function(str){return utils.isString(str)&&!!str.length;};utils.extend=function extend(){var options,name,src,copy,copyIsArray,clone,target=arguments[0]||{},i=1,length=arguments.length,deep=false;if(typeof target==="boolean"){deep=target;target=arguments[1]||{};i=2;}
if(typeof target!=="object"&&!utils.isFunction(target)){target={};}
if(length===i){return target;}
for(;i<length;i++){if((options=arguments[i])!==null){for(name in options){src=target[name];copy=options[name];if(target===copy){continue;}
if(deep&&copy&&(utils.isPlainObject(copy)||utils.isArray(copy))){copyIsArray=utils.isArray(copy);if(copyIsArray){copyIsArray=false;clone=src&&utils.isArray(src)?src:[];}else{clone=src&&utils.isObject(src)?src:{};}
target[name]=extend(deep,clone,copy);}else if(copy!==undefined){target[name]=copy;}}}}
return target;};utils.hasClass=function(node,className){if(node.nodeType===1){return node.className.split(' ').indexOf(className)>-1?true:false;}
return false;};utils.addClass=function(node,className){if(node.nodeType===1&&utils.isNonEmptyString(className)&&!utils.hasClass(node,className)){node.className+=' '+className.trim();}
return true;};utils.removeClass=function(node,className){var index,classes;if(node.nodeType===1&&utils.isNonEmptyString(className)&&utils.hasClass(node,className)){classes=node.className.split(' ');index=classes.indexOf(className);classes.splice(index,1);node.className=classes.join(' ');}
return true;};utils.writeScript=function(url){if(document.readyState!=="complete"||typeof QUnit==="object"){document.write('<scr'+'ipt src="'+url+'"></scr'+'ipt>');}};utils.hash=function(str,delimiter,pairing){var pair,value,idx,len,hash={};str=str.split(delimiter);for(idx=0,len=str.length;idx<len;idx+=1){value=str[idx];pair=value.split(pairing);if(pair.length>1){hash[pair[0].trim()]=pair.slice(1).join(pairing);}}
return hash;};utils.attach=function(scriptUrl,async){var tag=doc.createElement('script'),node=doc.getElementsByTagName('script')[0];tag.setAttribute('src',scriptUrl);tag.setAttribute('ftads','');if(async){tag.async='true';}
node.parentNode.insertBefore(tag,node);return tag;};utils.getReferrer=function(){return document.referrer||'';};utils.getPageType=function(){var targeting=FT.ads.config('dfp_targeting')||{};if(!FT._ads.utils.isPlainObject(targeting)){if(FT._ads.utils.isString(targeting)){targeting=FT._ads.utils.hash(targeting,';','=')||{};}}
return targeting.pt||'unknown';};utils.getLocation=function(){return document.location.href||'';};utils.getQueryString=function(){return document.location.search.substring(1)||'';};utils.getTimestamp=function(){var now=new Date();return[now.getFullYear(),('0'+(now.getMonth()+1)).slice(-2),('0'+now.getDate()).slice(-2),('0'+now.getHours()).slice(-2),('0'+now.getMinutes()).slice(-2),('0'+now.getSeconds()).slice(-2)].join("");};utils.nodeListToArray=function(obj){var array=[];for(var i=0;i<obj.length;i++){array[i]=obj[i];}
return array;};utils.init=function(){this.cookies=FT._ads.utils.hash(document.cookie,';','=');};FT._ads.utils=utils.extend(FT._ads.utils,utils);FT._ads.utils.init();return utils;}(window,document,FT));
(function(window,document,FT,undefined){FT=FT||{};FT._ads=FT._ads||{};FT._ads.utils=FT._ads.utils||{};var utils={},pluses=/\+/g,today=new Date();function raw(s){return s;}
function decoded(s){return decodeURIComponent(s.replace(pluses,' '));}
var config=utils.cookie=function(key,value,options){if(value!==undefined){options=FT._ads.utils.extend({},config.defaults,options);if(value===null){options.expires=-1;}
if(typeof options.expires==='number'){var days=options.expires,t=options.expires=new Date();t.setDate(t.getDate()+days);}
value=config.json?JSON.stringify(value):String(value);value=config.raw?value:encodeURIComponent(value);if(!!options.expires&&(options.expires.valueOf()-today.valueOf())<0){delete FT._ads.utils.cookies[encodeURIComponent(key)];}else{FT._ads.utils.cookies[encodeURIComponent(key)]=value;}
return(document.cookie=[encodeURIComponent(key),'=',value,options.expires?'; expires='+options.expires.toUTCString():'',options.path?'; path='+options.path:'',options.domain?'; domain='+options.domain:'',options.secure?'; secure':''].join(''));}
var decode=config.raw?raw:decoded;var cookie=FT._ads.utils.cookies[encodeURIComponent(key)];if(!!cookie||cookie===''){return config.json?JSON.parse(decode(cookie)):decode(cookie);}
return null;};config.defaults={};utils.removeCookie=function(key,options){if(utils.cookie(key)!==null){utils.cookie(key,null,options);return true;}
return false;};function getRegExp(name,param){var re,formats={"AYSC":"underscore","FT_U":"underscoreEquals","FT_Remember":"colonEquals","FT_User":"colonEquals","FTQA":"commaEquals"};switch(formats[name]){case"underscore":re='_'+param+'([^_]*)_';break;case"underscoreEquals":re='_'+param+'=([^_]*)_';break;case"colonEquals":re=':'+param+'=([^:]*)';break;case"commaEquals":re=param+'=([^,]*)';break;default:re=/((.|\n)*)/;break;}
return new RegExp(re);}
utils.getCookieParam=function(name,param){var matches,wholeValue=FT._ads.utils.cookie(name)||"";if(param){matches=wholeValue.match(getRegExp(name,param));}
return(matches&&matches.length)?matches[1]:undefined;};FT._ads.utils.cookie=utils.cookie;FT._ads.utils.removeCookie=utils.removeCookie;FT._ads.utils.getCookieParam=utils.getCookieParam;})(window,document,FT);
(function(window,document,FT,undefined){FT=FT||{};FT._ads=FT._ads||{};FT._ads.utils=FT._ads.utils||{};function now(){return(new Date()).valueOf();}
function Timer(interval,fn,maxTicks,opts){this.interval=(parseFloat(interval)||1)*1000;this.maxTicks=parseInt(maxTicks,10)||0;this.fn=fn;this.ticks=0;this.opts=opts||{};this.start();return this;}
Timer.prototype.tick=function(){var Timer=this;return function(){Timer.ticks++;Timer.fn.apply(Timer);Timer.lastTick=now();if(Timer.ticks===Timer.maxTicks){Timer.stop();}};};Timer.prototype.start=function(){this.startTime=this.lastTick=now();this.id=setInterval(this.tick(),this.interval);return true;};Timer.prototype.resume=function(){if(this.timeLeft){this.id=setInterval(this.tick(),this.timeLeft);delete this.timeLeft;return true;}
return false;};Timer.prototype.pause=function(){if(this.id){this.timeLeft=(this.interval)-(now()-this.lastTick);this.kill();return true;}
return false;};Timer.prototype.reset=function(){if(!!this.startTime){this.startTime=now();this.ticks=1;return true;}else{return false;}};Timer.prototype.kill=function(){if(this.id){clearInterval(this.id);delete this.id;return true;}
return false;};Timer.prototype.stop=function(){if(this.id||this.timeLeft){this.ticks=0;this.kill();delete this.timeLeft;return true;}
return false;};function Timers(){var scope=this;this.timers=[];function all(method){return function(){var timer,i=scope.timers.length-1;while(timer=scope.timers[i]){timer[method]();i--;}};}
function hasExecutionPaused(fn){return function(){var Timer=this,reset=Timer.opts.reset||false,time=now()-Timer.lastTick-Timer.interval,threshhold=Timer.interval*1.5;if(threshhold<time){if(reset){Timer.reset();}}
fn.apply(Timer);};}
function create(interval,fn,maxTicks,opts){if((opts&&opts.reset)){fn=hasExecutionPaused(fn);}
timer=new Timer(interval,fn,maxTicks,opts);scope.timers.push(timer);return timer;}
return{create:create,resumeall:all('resume'),pauseall:all('pause'),stopall:all('stop')};}
FT._ads.utils.timers=new Timers();})(window,document,FT);
(function(window,document,FT,undefined){FT=FT||{};FT._ads=FT._ads||{};utils=FT._ads.utils=FT._ads.utils||{};var callback,viewPorts,current,timer=false;function getViewportDims(){var e=window,a='inner';if(!('innerWidth'in window)){a='client';e=document.documentElement||document.body;}
return{w:e[a+'Width'],h:e[a+'Height']};}
function getNearestBreakpoint(){var viewPort,viewPortDims,current,winner,dims=getViewportDims();for(viewPort in viewPorts){viewPortDims=viewPorts[viewPort];if(dims.w>viewPortDims[0]&&dims.h>viewPortDims[1]){if(!winner||viewPortDims[0]>viewPorts[winner][0]){winner=viewPort;}}}
return winner;}
function fire(){var winner=getNearestBreakpoint();if(current!==winner){setCurrent(winner);callback(winner);}}
function setCurrent(name){current=name;}
function onResize(){if(timer){clearTimeout(timer);}
timer=setTimeout(fire,200);}
function init(vps,cb){if(!utils.isFunction(cb)){return false;}
viewPorts=vps;callback=cb;setCurrent(getNearestBreakpoint());if(window.addEventListener){window.addEventListener("resize",onResize,false);}
else if(document.body.attachEvent){document.body.attachEvent("onresize",onResize);}
return function(){return current;};}
utils.responsive=init;})(window,document,FT);
(function(win,doc,undefined){"use strict";function Config(){var defaults={network:'5887',formats:{intro:{},banlbGPT:{sizes:[[728,90],[468,60],[970,90],[970,66],[970,250]],outOfPage:true},mpu:{sizes:[[300,250],[336,280]]},doublet:{sizes:[[352,230]]},hlfmpu:{sizes:[[300,250],[300,600],[336,850],[336,280],[300,1050]]},newssubs:{sizes:[[270,42]]},refresh:{'sz':'1x1'},searchbox:{sizes:[[270,42]]},tlbxrib:{sizes:[[336,60]]},marketingrib:{sizes:[[336,60]]},lhn:{sizes:[[136,64]]},tradcent:{sizes:[[336,260]]},mktsdata:{sizes:[[88,31],[75,25]]},mpusky:{sizes:[[300,250],[336,280],[160,60]]},wdesky:{sizes:[[160,600]]}},audSciLimit:35,collapseEmpty:'ft'};var store={};var fetchMetaConfig=function(){var meta,results={},metas=doc.getElementsByTagName('meta');for(var i=0;i<metas.length;i++){meta=metas[i];if(meta.name){if(meta.getAttribute("data-contenttype")==="json"){results[meta.name]=(window.JSON)?JSON.parse(meta.content):"UNSUPPORTED";}else{results[meta.name]=meta.content;}}}
return results;};var fetchGlobalConfig=function(){if(FT._ads.utils.isObject(FT.env)){return FT.env;}else{return{};}};var fetchCookieConfig=function(){return FT._ads.utils.cookies;};function setDFPSiteForEnv(){var env,site=store.dfp_site;if(FT.Properties&&FT.Properties.ENV){env=FT.Properties.ENV.toLowerCase();if(env!=='p'){site=site.replace(/^\w+\./,"test.");store.dfp_site=site;}}}
var access=function(k,v){var result;if(FT._ads.utils.isPlainObject(k)){store=FT._ads.utils.extend(store,k);result=store;}else if(typeof v==="undefined"){if(typeof k==="undefined"){result=store;}else{result=store[k];}}else{store[k]=v;result=v;}
return result;};access.clear=function(key){if(key){delete store[key];}else{store={};}};access.load=function(clear){if(!!clear){access.clear();}
if(FT._ads.utils.isString(FT._ads.utils.cookie('ftads:mode_t'))){if(FT._ads.utils.cookie('ftads:mode_t')==="testuser"){store=FT._ads.utils.extend({},defaults,fetchMetaConfig(),fetchGlobalConfig(),fetchCookieConfig());var siteCookie=FT._ads.utils.cookie('ftads:dfpsite');if(siteCookie&&(siteCookie==='test'||siteCookie==='ftcom')){var splitSite=(store.dfp_site||'').split('.');splitSite[0]=siteCookie;store.dfp_site=splitSite.join('.');}else{setDFPSiteForEnv();}}}else{store=FT._ads.utils.extend({},defaults,fetchMetaConfig(),fetchGlobalConfig());setDFPSiteForEnv();}
return store;};access.load();return access;}
FT._ads.utils.extend(FT.ads,{config:new Config()});}(window,document));
(function(win,doc,undefined){"use strict";var Metadata={};Metadata.getLoginInfo=function(){var loggedIn=false,eid=FT._ads.utils.getCookieParam('FT_U','EID')||null,remember=FT._ads.utils.cookie('FT_Remember');if(!eid&&remember&&FT._ads.utils.isFunction(remember.split)){remember=remember.split(':');eid=!!(remember[0].length)?remember[0]:eid;}
if(eid||FT._ads.utils.cookie('FTSession')){loggedIn=true;}
return{eid:eid,loggedIn:loggedIn};};Metadata.getAyscVars=function(obj){var subsLevelReplaceLookup={'edt':{'22':/^edit$/,'97':/^.*/},'int':{'22':/^Ftemp$/,'97':/^.*/},'cor':{'22':/^[N]*[PL][01][PL]*[1]*[PL][12][A-Za-z][A-Za-z]/,'97':/^c$/},'lv1':{'22':/^[PL]*[0]*[PL]1[A-Za-z][A-Za-z]/,'97':/^[^c]$/},'lv2':{'22':/^[N]*[PL]*[0]*[PL]2[A-Za-z][A-Za-z]/,'97':/^[^c]$/},'reg':{'22':/^[PL]0[A-Za-z][A-Za-z]/,'97':/^[^c]$/}},regex_key_names=['22','97'],leading_zero_key_names=['19','21'],substr_key_names=['24=0=3=cn'];function fieldSubstr(SubStrKeyNames,obj){var i,value;for(i=0;i<SubStrKeyNames.length;i++){value=FT._ads.utils.isString(obj)?obj.charAt(i):obj[i];if(value===false){continue;}
else{var SubStrItems=SubStrKeyNames[i].split("="),ayscField=SubStrItems[0],val=obj[ayscField],newField;if(val!==undefined){newField=SubStrItems[3];obj[newField]=val.substring(SubStrItems[1],SubStrItems[2]);}}
return obj;}}
function detectERights(obj){if(FT._ads.utils.cookie("FT_U")){var erights=FT._ads.utils.cookie("FT_U").split("="),keyname=erights[0],val=erights[1];if((keyname!==undefined)&&(val===undefined)){obj[keyname]=val;}}
return obj;}
function stripLeadingZeros(KeysToStrip,obj){var idx,l;for(idx=0,l=KeysToStrip.length;idx<l;idx++){if(obj[KeysToStrip[idx]]){obj[KeysToStrip[idx]]=obj[KeysToStrip[idx]].replace(/^0+/,"");}}
return obj;}
function fieldRegex(RegexKeyNames,obj){var prop;function innerReplace(keyName,property){var value=obj[keyName];if(value===undefined){return;}else if((myState!=="failed")&&(value.match(property[keyName]))){myState="passed";}else{myState="failed";return;}}
for(prop in subsLevelReplaceLookup){var myState="initial";if(subsLevelReplaceLookup.hasOwnProperty(prop)){for(var i=0;i<RegexKeyNames.length;i++){innerReplace(RegexKeyNames[i],subsLevelReplaceLookup[prop]);}
if(myState==="passed"){obj.slv=prop;}}}
return obj;}
function prepareAdVars(AllVars){AllVars=stripLeadingZeros(leading_zero_key_names,AllVars);AllVars=fieldRegex(regex_key_names,AllVars);AllVars=fieldSubstr(substr_key_names,AllVars);AllVars=detectERights(AllVars);return AllVars;}
var out={},item,q;if(FT._ads.utils.cookie("AYSC")){q=FT._ads.utils.cookie("AYSC").split("_");for(var i=0,j=q.length;i<j;i++){item=q.pop();if(!!item){var key,val,m=item.match(/^(\d\d)([^_]+)/);if(m){key=m[1];val=m[2];out[key]=val;}}}}
var x=prepareAdVars(out);return FT._ads.utils.extend({},obj,x);};Metadata.user=function(){var ayscProp,ayscVal,asyc=this.getAyscVars({}),result={},valueFilter=/(PVT)|(x+)/i,loginInfo=this.getLoginInfo(),ayscProps={homepage_edition:'28',corporate_access_id_code:'27',phone_area_code:'26',continent:'24',subscription_level:'slv',active_personal_investor:'20',company_size:'19',post_code:'12',job_position:'07',job_responsibility:'06',industry:'05',state:'04',gender:'02',DB_company_size:'40',DB_industry:'41',DB_company_turnover:'42',cameo_country_code:'43',cameo_local_code:'44',DB_country_code:'45',cameo_investor_code:'46',cameo_property_code:'51'};for(ayscProp in ayscProps){ayscVal=asyc[ayscProps[ayscProp]];if(ayscVal&&!(valueFilter.test(ayscVal))){result[ayscProp]=ayscVal;}}
result.eid=loginInfo.eid;result.loggedIn=loginInfo.loggedIn;return result;};Metadata.page=function(){var result={};result.uuid=window.pageUUID?window.pageUUID:FT._ads.utils.isFunction(window.getUUIDFromString)?getUUIDFromString(document.location.href):undefined;result.auuid=window.articleUUID||undefined;result.dfpSite=FT.ads.config('dfp_site');result.dfpZone=FT.ads.config('dfp_zone');if(FT._ads.utils.isNonEmptyString(window.siteMapTerm)){result.siteMapTerm=window.siteMapTerm;}
if(FT._ads.utils.isNonEmptyString(window.navEdition)){result.navEdition=window.navEdition;}
if(FT._ads.utils.isNonEmptyString(window.brandName)){result.brandName=window.brandName;}
if(FT._ads.utils.isNonEmptyString(window.primaryThemeName)){result.primaryThemeName=window.primaryThemeName;}
return result;};FT._ads.utils.extend(FT.ads,{metadata:Metadata});}(window,document));
(function(win,doc,undefined){"use strict";var proto=Krux.prototype;function Krux(){}
proto.init=function(){if(FT.ads.config('krux')&&FT.ads.config('krux').id){if(!window.Krux){((window.Krux=function(){window.Krux.q.push(arguments);}).q=[]);}
var m,src=(m=location.href.match(/\bkxsrc=([^&]+)/))&&decodeURIComponent(m[1]),finalSrc=/^https?:\/\/([^\/]+\.)?krxd\.net(:\d{1,5})?\//i.test(src)?src:src==="disable"?"":"//cdn.krxd.net/controltag?confid="+FT.ads.config('krux').id;FT._ads.utils.attach(finalSrc,true);this.events.init();}else{}};proto.retrieve=function(name){var value;name='kx'+name;if(window.localStorage&&localStorage.getItem(name)){value=localStorage.getItem(name);}else if(FT._ads.utils.cookie(name)){value=FT._ads.utils.cookie(name);}
return value;};proto.segments=function(){return this.retrieve('segs');};proto.targeting=function(){var bht=false,segs=this.segments();if(segs){segs=segs.split(',');if(FT.ads.config('krux').limit){segs=segs.slice(0,FT.ads.config('krux').limit);}}
return{"kuid":this.retrieve('user'),"ksg":segs,"khost":encodeURIComponent(location.hostname),"bht":segs&&segs.length>0?'true':'false'};};proto.events={dwell_time:function(config){if(config){var fire=this.fire,interval=config.interval||5,max=(config.total/interval)||120,uid=config.id;FT._ads.utils.timers.create(interval,(function(){return function(){fire(uid,{dwell_time:(this.interval*this.ticks)/1000});};}()),max,{reset:true});}}};proto.events.fire=function(id,attrs){if(id){attrs=FT._ads.utils.isPlainObject(attrs)?attrs:{};return window.Krux('admEvent',id,attrs);}
return false;};proto.events.init=function(){var event,configured=FT.ads.config('krux')&&FT.ads.config('krux').events;if(FT._ads.utils.isPlainObject(configured)){for(event in configured){if(FT._ads.utils.isFunction(this[event])){this[event](configured[event]);}else if(FT._ads.utils.isFunction(configured[event].fn)){configured[event].fn(configured[event]);}}}};FT._ads.utils.extend(FT.ads,{krux:new Krux()});}(window,document));
(function(win,doc,undefined){"use strict";var proto=Chartbeat.prototype;function Chartbeat(){}
proto.init=function(){this.decorateRefresh();};proto.decorateRefresh=function(){if(FT._ads.utils.isFunction(FT.ads.gpt.refresh)){var _refresh=FT.ads.gpt.refresh;FT.ads.gpt.refresh=this.refresh(_refresh);return true;}};proto.refresh=function(fn){return function(slotsForRefresh){if(window.pSUPERFLY){var slot,slotName,cbName,slots=FT.ads.slots;slotsForRefresh=slotsForRefresh||slots;for(slotName in slotsForRefresh){slot=slots[slotName];if(slot.gptSlot&&slot.timer===undefined){if(FT._ads.utils.isNonEmptyString(cbName=slot.container.getAttribute('data-cb-ad-id'))){window.pSUPERFLY.refreshAd(cbName);}}}}
fn.apply(this,arguments);};};FT._ads.utils.extend(FT.ads,{cb:new Chartbeat()});}(window,document));
(function(win,doc,undefined){"use strict";var proto=Targeting.prototype;proto.init=false;function Targeting(){var context=this,parameters={};return function(){var item,config={metadata:context.getFromMetaData,audSci:context.fetchAudSci,krux:context.fetchKrux,socialReferrer:context.getSocialReferrer,pageReferrer:context.getPageReferrer,cookieConsent:context.cookieConsent,timestamp:context.timestamp,version:context.version};parameters=FT._ads.utils.extend({},context.getFromConfig(),context.encodedIp(),context.getAysc(),context.searchTerm());for(item in config){if(FT.ads.config(item)){FT._ads.utils.extend(parameters,config[item]());}}
proto.init=true;return parameters;};}
proto.getFromMetaData=function(){var page=FT.ads.metadata.page(),user=FT.ads.metadata.user();return{eid:user.eid||null,fts:user.loggedIn+'',uuid:page.uuid,auuid:page.auuid};};proto.encodedIp=function(){var DFPPremiumIPReplaceLookup={'0':{'replaceRegex':/0/g,'replaceValue':'a'},'1':{'replaceRegex':/1/g,'replaceValue':'b'},'2':{'replaceRegex':/2/g,'replaceValue':'c'},'3':{'replaceRegex':/3/g,'replaceValue':'d'},'4':{'replaceRegex':/4/g,'replaceValue':'e'},'5':{'replaceRegex':/5/g,'replaceValue':'f'},'6':{'replaceRegex':/6/g,'replaceValue':'g'},'7':{'replaceRegex':/7/g,'replaceValue':'h'},'8':{'replaceRegex':/8/g,'replaceValue':'i'},'9':{'replaceRegex':/9/g,'replaceValue':'j'},'.':{'replaceRegex':/\./g,'replaceValue':'z'}};function getIP(){var ip,tmp,ftUserTrackVal=FT._ads.utils.cookie('FTUserTrack'),ipTemp;if(ftUserTrackVal){ip=ftUserTrackVal;tmp=ftUserTrackVal.match(/^\w{1,3}\.\w{1,3}\.\w{1,3}\.\w{1,3}\.\w+$/);if(tmp){tmp=tmp[0];ipTemp=tmp.match(/\w{1,3}/g);if(ipTemp){ip=ipTemp[0]+"."+ipTemp[1]+"."+ipTemp[2]+"."+ipTemp[3];}}}
return ip;}
function encodeIP(ip){var encodedIP,lookupKey;if(ip){encodedIP=ip;for(lookupKey in DFPPremiumIPReplaceLookup){encodedIP=encodedIP.replace(new RegExp(DFPPremiumIPReplaceLookup[lookupKey].replaceRegex),DFPPremiumIPReplaceLookup[lookupKey].replaceValue);}}
return encodedIP;}
return{loc:encodeIP(getIP())};};proto.getFromConfig=function(){var targeting=FT.ads.config('dfp_targeting')||{};if(!FT._ads.utils.isPlainObject(targeting)){if(FT._ads.utils.isString(targeting)){targeting=FT._ads.utils.hash(targeting,';','=')||{};}}
return targeting;};proto.fetchAudSci=function(rsiSegs){var segments={};if(!proto.init){FT._ads.utils.attach("//js.revsci.net/gateway/gw.js?csid=J07717",true);}
function parseSegs(segs,max){var match,exp=/J07717_10*([^|]*)/g,found=[];if(max&&segs){while((match=exp.exec(segs))&&(found.length<max)){found.push('z'+match[1]);}}
return(found.length)?found:false;}
if(typeof rsiSegs==="undefined"){rsiSegs=FT._ads.utils.cookie('rsi_segs');}
segments=parseSegs(rsiSegs,FT.ads.config('audSciLimit'));return segments?{a:segments}:{};};proto.fetchKrux=function(){return FT.ads.krux?FT.ads.krux.targeting():{};};proto.getPageReferrer=function(){var match=null,referrer=FT._ads.utils.getReferrer(),hostRegex;if(referrer!==''){hostRegex=/^.*?:\/\/.*?(\/.*)$/;match=hostRegex.exec(referrer)[1];if(match!==null){match.substring(1);}}
return match&&{rf:match.substring(1)}||{};};proto.getSocialReferrer=function(){var codedValue,refUrl,referrer=FT._ads.utils.getReferrer(),lookup={'t.co':'twi','facebook.com':'fac','linkedin.com':'lin','drudgereport.com':'dru'},refererRegexTemplate='^http(|s)://(www.)*(SUBSTITUTION)/|_i_referer=http(|s)(:|%3A)(\/|%2F){2}(www.)*(SUBSTITUTION)(\/|%2F)';if(FT._ads.utils.isString(referrer)){for(refUrl in lookup){var refererRegex=new RegExp(refererRegexTemplate.replace(/SUBSTITUTION/g,refUrl));if(refUrl!==undefined&&refererRegex.test(referrer)){codedValue=lookup[refUrl];break;}}}
return codedValue&&{socref:codedValue}||{};};proto.cookieConsent=function(){return{cc:FT._ads.utils.cookie('cookieconsent')==='accepted'?'y':'n'};};proto.getAysc=function(){var exclusions=['key=03','key=04','key=08','key=09','key=10','key=11','key=12','key=13','key=15','key=16','key=17','key=18','key=22','key=23','key=24','key=25','key=26','key=28','key=29','key=30','key=96','key=98'];var remove_exes={'02':1,'05':1,'06':1,'07':1,'19':1,'20':1,'21':1};var remove_res_pvt={'14':1,'cn':1,'27':1};var returnObj={};var AllVars=FT.ads.metadata.getAyscVars({});function excludeFields(exclusions,obj){var idx,keyvalsplit,prop;for(prop in obj){for(idx=0;idx<exclusions.length;idx++){keyvalsplit=exclusions[idx].split("=");if(((keyvalsplit[0]==="key")&&(prop===keyvalsplit[1]))||((keyvalsplit[0]==="val")&&(obj[prop]===keyvalsplit[1]))){delete obj[prop];}}}
return obj;}
AllVars=excludeFields(exclusions,AllVars);for(var ayscVar in AllVars){if(!AllVars[ayscVar]){continue;}
if(remove_exes[ayscVar]&&/^x+$/i.test(AllVars[ayscVar])){continue;}
if(remove_res_pvt[ayscVar]&&/^pvt|res$/i.test(AllVars[ayscVar])){continue;}
returnObj[ayscVar]=AllVars[ayscVar].toString().toLowerCase();}
return returnObj;};proto.behaviouralFlag=function(){var flag=(typeof this.rsiSegs()==="undefined")?"false":"true";return flag;};proto.searchTerm=function(){var qs=FT._ads.utils.hash(FT._ads.utils.getQueryString(),/\&|\;/,'='),keywords=qs.q||qs.s||qs.query||qs.queryText||qs.searchField||undefined;if(keywords&&keywords!==''){keywords=unescape(keywords).toLowerCase().replace(/[';\^\+]/g,' ').replace(/\s+/g,' ').trim();}
return{kw:keywords};};proto.timestamp=function(){return{ts:FT._ads.utils.getTimestamp()};};proto.version=function(){return{ver:"gpt-"+FT.ads.version.artifactVersion};};FT._ads.utils.extend(FT.ads,{targeting:new Targeting()});}(window,document));
FT.analytics=FT.analytics||{};FT.analytics.audienceScience={addEncToLoc:function(){if(typeof DM_addEncToLoc==="function"){return DM_addEncToLoc.apply(this,arguments);}},addToLoc:function(){if(typeof DM_addToLoc==="function"){DM_addToLoc.apply(this,arguments);}},cat:function(){if(typeof DM_cat==="function"){DM_cat.apply(this,arguments);}},name:function(){if(typeof DM_name==="function"){DM_name.apply(this,arguments);}},keywords:function(){if(typeof DM_keywords==="function"){DM_keywords.apply(this,arguments);}},event:function(){if(typeof DM_event==="function"){DM_event.apply(this,arguments);}},setLoc:function(){if(typeof DM_setLoc==="function"){DM_setLoc.apply(this,arguments);}},tag:function(){if(typeof DM_tag==="function"){return DM_tag.apply(this,arguments);}}};
FT.analytics.audSciPollCount=0;FT.analytics.maxAudSciPollCount=10;FT.analytics.audSciPollCountInterval=30;FT.analytics.populateAudSci=function(){var rsiAYSC=document.cookie.match(/AYSC=([^;]*)/)?RegExp.$1:"",rsiPos=rsiAYSC.match(/_07([^_]*)/)?RegExp.$1:null,rsiResp=rsiAYSC.match(/_06([^_]*)/)?RegExp.$1:null,rsiInd=rsiAYSC.match(/_05([^_]*)/)?RegExp.$1:null,rsiCoun=rsiAYSC.match(/_14([^_]*)/)?RegExp.$1:null,rsiCompSize=rsiAYSC.match(/_19([^_]*)/)?RegExp.$1:null,temppos=typeof rsiPos!=="undefined"?rsiPos:"undefined",tempresp=typeof rsiResp!=="undefined"?rsiResp:"undefined",tempind=typeof rsiInd!=="undefined"?rsiInd:"undefined",tempcountry=typeof rsiCoun!=="undefined"?rsiCoun:"undefined",tempcompsize=typeof rsiCompSize!=="undefined"?rsiCompSize:"undefined",rsi_call="<script type=\"text\/javascript\">",tempsec=typeof FTSection!=="undefined"?FTSection:"undefined",temppage=typeof FTPage!=="undefined"?FTPage:"undefined";FT.analytics.audienceScience.addEncToLoc("FTSectionCode",tempsec);FT.analytics.audienceScience.addEncToLoc("FTPageCode",temppage);FT.analytics.audienceScience.addEncToLoc("FTP",temppos);FT.analytics.audienceScience.addEncToLoc("FTR",tempresp);FT.analytics.audienceScience.addEncToLoc("FTI",tempind);FT.analytics.audienceScience.addEncToLoc("FTC",tempcountry);FT.analytics.audienceScience.addEncToLoc("FTCS",tempcompsize);FT.analytics.audienceScience.addEncToLoc("SubsLevel",FT.ads.metadata.user().subscription_level||"anon");if(FT&&FT.env&&FT.env.dfp_site&&FT.env.dfp_zone){FT.analytics.audienceScience.addEncToLoc('dfp_site',FT.env.dfp_site);FT.analytics.audienceScience.addEncToLoc('dfp_zone',FT.env.dfp_zone);}
FT.analytics.audienceScience.tag();};FT.analytics.pollAudSci=function(){FT.analytics.audSciPollCount++;if((typeof DM_addEncToLoc!=="undefined")&&(typeof FT.analytics.audienceScience!=="undefined")){FT.analytics.populateAudSci();}
else if(FT.analytics.audSciPollCount<FT.analytics.maxAudSciPollCount){setTimeout(FT.analytics.pollAudSci,FT.analytics.audSciPollCountInterval);}};FT.analytics.pollAudSci();
(function(win,doc,undefined){"use strict";var buildURLForVideo=function(zone,pos,vidKV){pos=pos||'video';vidKV=vidKV||{};var gptVideoURL=function(){var URL;var dfp_targeting;var encodeCustParams=function(vkv){var allTargeting=FT.ads.targeting();var results='',rsiSegs=allTargeting.a,kruxSegs=allTargeting.ksg,includeParams=['playlistid','playerid','07','ksg','a','06','slv','eid','05','19','21','27','20','02','14','cn','01','rfrsh','dcopt','brand','section','lnID','specialBadging'];var i;for(i=0;i<includeParams.length;i++){var key=includeParams[i];var value=false;if(typeof allTargeting[key]!=='undefined'){value=allTargeting[key];}else if(typeof vkv!=='undefined'&&(typeof vkv[key]!=='undefined')){value=vkv[key];}
if(key==='ksg'&&kruxSegs){value=kruxSegs.slice(0,FT.ads.config('kruxMaxSegs')).join(',');}
if(key==='a'&&rsiSegs){value=rsiSegs.slice(0,FT.ads.config('audSciLimit')).join(',');}
results+=!value?'':key+'='+value+'&';}
return encodeURIComponent(results);};URL="http://pubads.g.doubleclick.net/gampad/ads?env=vp&gdfp_req=1&impl=s&output=xml_vast2&iu=/5887/"+FT.ads.config('dfp_site')+"/"+FT.ads.config('dfp_zone')+"&sz=592x333&unviewed_position_start=1&scp=pos%3D"+pos;return{urlStem:URL,additionalAdTargetingParams:encodeCustParams(vidKV)};};var legacyVideoURL=function(mode,vkv){var URL;var keyOrderVideo=['dcopt','pos'];var keyOrderVideoExtra=['dcopt','brand','section','playlistid','playerid','07','ksg','a','06','slv','eid','05','19','21','27','20','02','14','cn','01','rfrsh'];var encodeBaseAdvertProperties=function(mode,vidKV){var allTargeting=FT.ads.targeting();var results='',dfp_targeting=FT.ads.config('dfp_targeting'),rsiSegs=allTargeting.a,kruxSegs=allTargeting.ksg,order;if(mode==='video'){order=keyOrderVideo;}
if(mode==='videoExtra'){order=keyOrderVideoExtra;}
var i;for(i=0;i<order.length;i++){var key=order[i];var value=false;if(typeof allTargeting[key]!=='undefined'){value=allTargeting[key];}else if(typeof vidKV!=='undefined'&&(typeof vidKV[key]!=='undefined')){value=vidKV[key];}
if(key==='pos'&&dfp_targeting){results+=dfp_targeting+';';}
if(key==='ksg'&&kruxSegs){value=kruxSegs.slice(0,FT.ads.config('kruxMaxSegs')).join(';ksg=');}
if(key==='a'&&rsiSegs){value=rsiSegs.slice(0,FT.ads.config('audSciLimit')).join(';a=');}
results+=!value?'':key+'='+value+';';}
return results.replace(/;$/,'');};URL="http://ad.uk.doubleclick.net/N5887/pfadx/"+FT.ads.config('dfp_site')+"/"+FT.ads.config('dfp_zone')+";sz=592x333,400x225;pos=video;";URL+=encodeBaseAdvertProperties('video');return{urlStem:URL,additionalAdTargetingParams:encodeBaseAdvertProperties('videoExtra',vidKV)};};if(FT.ads.config('video')){return gptVideoURL();}
if(!FT.ads.config('video')){return legacyVideoURL();}};FT._ads.utils.extend(FT.ads,{buildURLForVideo:buildURLForVideo});}(window,document));
(function(win,doc,undefined){"use strict";var proto=Slots.prototype;function Slots(){}
proto.fetchSlotConfig=function(container,slotName,config){if(slotName==="searchbox"){slotName="newssubs";}
var attrs,attr,attrObj,name,matches,parser,sizes=[],targeting={pos:slotName},parsers={'size':function(name,value){value.replace(/(\d+)x(\d+)/g,function(match,width,height){sizes.push([parseInt(width,10),parseInt(height,10)]);});return!!sizes.length?sizes:false;},'position':function(name,value){targeting.pos=value;return value;},'out-of-page':function(){config.outOfPage=true;return true;},'page-type':function(name,value){targeting.pt=value;return value;},'targeting':function(name,value){if(value!==undefined){value=FT._ads.utils.hash(value,';','=');targeting=FT._ads.utils.extend(targeting,value);}
return value;},'default':function(name,value){targeting[name]=value;return value;}};attrs=container.attributes;for(attr in attrs){attrObj=attrs[attr];if(Object.prototype.hasOwnProperty.call(attrs,attr)&&attrObj.name&&!!(matches=attrObj.name.match(/(data-)?(ad|ftads)-(.+)/))){name=matches[3];parser=FT._ads.utils.isFunction(parsers[name])?parsers[name]:parsers['default'];parser(name,attrObj.value);}}
return{sizes:!!(sizes.length)?sizes:config.sizes,outOfPage:config.outOfPage||false,collapseEmpty:config.collapseEmpty,targeting:targeting,cbTrack:config.cbTrack};};proto.addContainer=function(node,id){var container=doc.createElement('div');container.setAttribute('id',id);if(node.tagName==='SCRIPT'){if(node.id===id){node.removeAttribute('id');}
node.parentNode.insertBefore(container,node);}else{node.appendChild(container);}
return container;};proto.centerContainer=function(container){FT._ads.utils.addClass(container,'center');};proto.addChartBeatTracking=function(container,slotName){container.setAttribute('data-cb-ad-id',slotName);};proto.collapse=function(slotNames){var slotName,result=false;if(!FT._ads.utils.isArray(slotNames)){slotNames=[slotNames];}
while(slotName=slotNames.pop()){if(this[slotName]&&FT._ads.utils.isFunction(this[slotName].collapse)){this[slotName].collapse();result=true;}}
return result;};proto.uncollapse=function(slotNames){var slotName,result=false;if(!FT._ads.utils.isArray(slotNames)){slotNames=[slotNames];}
while(slotName=slotNames.pop()){if(this[slotName]&&FT._ads.utils.isFunction(this[slotName].uncollapse)){this[slotName].uncollapse();result=true;}}
return result;};proto.initSlot=function(slotName){if(this[slotName]){return false;}
var container=doc.getElementById(slotName),formats=FT.ads.config('formats');if(!container){return false;}
var config=this.fetchSlotConfig(container,slotName,formats[slotName]||{});if(!config.sizes){return false;}
if(container.tagName==='SCRIPT'){container=this.addContainer(container,slotName);}
this.centerContainer(container,config.sizes);if(config.cbTrack){this.addChartBeatTracking(container,slotName);}
this[slotName]={container:container,config:config,collapse:function(){FT._ads.utils.addClass(this.container,'empty');FT._ads.utils.addClass(document.body,'no-'+container.id);},uncollapse:function(){FT._ads.utils.removeClass(this.container,'empty');FT._ads.utils.removeClass(document.body,'no-'+container.id);}};FT.ads.gpt.defineSlot(slotName);return this[slotName];};FT._ads.utils.extend(FT.ads,{slots:new Slots()});}(window,document));
(function(win,doc,undefined){"use strict";var proto=GPT.prototype;function GPT(){win.googletag=win.googletag||{};win.googletag.cmd=win.googletag.cmd||[];return this;}
proto.defineSlot=function(slotName){var context=this,slot=FT.ads.slots[slotName],slotId=slotName+'-gpt',wrap=FT.ads.slots.addContainer(slot.container,slotId),responsive=FT.ads.config('responsive');FT._ads.utils.addClass(wrap,'wrap');googletag.cmd.push(function(context,slot,slotName,slotId){return function(){var currentSize;if(FT._ads.utils.isObject(responsive)&&FT._ads.utils.isObject(slot.config.sizes)){currentSize=slot.config.sizes[context.responsive()];var sizeMapping=context.buildSizeMapping(responsive,slot.config.sizes);slot.gptSlot=googletag.defineSlot(context.getUnitName(slotName),[0,0],slotId);slot.gptSlot.defineSizeMapping(sizeMapping);}else{currentSize=slot.config.sizes;slot.gptSlot=googletag.defineSlot(context.getUnitName(slotName),slot.config.sizes,slotId);}
slot.gptSlot.addService(googletag.pubads());context.setSlotCollapseEmpty(slot.gptSlot,slot.config);context.setSlotTargeting(slot.gptSlot,slot.config.targeting);context.addCompanionService(slot);if(currentSize!==false){googletag.cmd.push(googletag.display(slotId));}};}(this,slot,slotName,slotId));if(slot.config.outOfPage){googletag.cmd.push(this.defineOutOfPage(this,slotName));}
return slot;};proto.defineOutOfPage=function(context,slotName){var slot=FT.ads.slots[slotName],slotId=slotName+'-oop';FT.ads.slots.addContainer(slot.container,slotId);return function(){var oopSlot;oopSlot=googletag.defineOutOfPageSlot(context.getUnitName(slotName),slotId).addService(googletag.pubads());slot.oopSlot=oopSlot;context.setSlotTargeting(oopSlot,slot.config.targeting);googletag.cmd.push(googletag.display(slotId));};};proto.getUnitName=function(slotName){var unitName,gptUnitName=FT.ads.config('gptUnitName'),site=FT.ads.config('dfp_site'),zone=FT.ads.config('dfp_zone');if(FT._ads.utils.isNonEmptyString(gptUnitName)){unitName=gptUnitName;}else{unitName='/'+FT.ads.config('network');unitName+=FT._ads.utils.isNonEmptyString(site)?'/'+site:'';unitName+=FT._ads.utils.isNonEmptyString(zone)?'/'+zone:'';}
return unitName;};proto.setPageTargeting=function(){var param,targeting=FT.ads.targeting();function setTargeting(key,value){return function(){googletag.pubads().setTargeting(key,value);};}
for(param in targeting){googletag.cmd.push(setTargeting(param,targeting[param]));}
return targeting;};proto.addCompanionService=function(slot){if(FT.ads.config('companions')&&slot.config.companion!==false){slot.gptSlot.addService(googletag.companionAds());}
return slot;};proto.updateCorrelator=function(slot){googletag.cmd.push(function(){googletag.pubads().updateCorrelator();});};proto.refresh=function(slotsForRefresh){var slot,slots=FT.ads.slots;slotsForRefresh=slotsForRefresh||[];if(slotsForRefresh.length===0){for(slot in slots){slot=slots[slot];if(slot.gptSlot&&slot.timer===undefined){slot.gptSlot.setTargeting('rfrsh','true');slotsForRefresh.push(slot.gptSlot);}}}
googletag.pubads().refresh(slotsForRefresh);};proto.startRefresh=function(){var refreshConfig=FT.ads.config('refresh')||{},pageType=FT._ads.utils.getPageType(),time=(refreshConfig[pageType]&&refreshConfig[pageType].time)||refreshConfig.time||false,max=(refreshConfig[pageType]&&refreshConfig[pageType].max)||refreshConfig.max||0;if(time){this.refreshTimer=FT._ads.utils.timers.create(time,function(){FT.ads.gpt.refresh();},max);}};proto.pauseRefresh=function(){if(this.refreshTimer){this.refreshTimer.pause();}};proto.resumeRefresh=function(){if(this.refreshTimer){this.refreshTimer.resume();}};proto.stopRefresh=function(){if(this.refreshTimer){this.refreshTimer.stop();}};proto.setPageCollapseEmpty=function(){var mode=FT.ads.config('collapseEmpty');if(mode==='after'||mode===undefined){mode=undefined;}else if(mode==='before'||mode===true){mode=true;}else if(mode==='never'||mode===false){mode=false;}
googletag.cmd.push(function(){googletag.pubads().collapseEmptyDivs(mode);});return mode;};proto.enableVideo=function(){if(FT.ads.config('video')){googletag.pubads().enableVideoAds();}};proto.enableCompanions=function(){if(FT.ads.config('companions')){googletag.pubads().disableInitialLoad();googletag.companionAds().setRefreshUnfilledSlots(true);}};proto.buildSizeMapping=function(viewports,slotSizes){var size,viewport,mapping=googletag.sizeMapping();for(viewport in slotSizes){if(slotSizes[viewport]){mapping.addSize(viewports[viewport],slotSizes[viewport]);}}
mapping=mapping.build();return mapping;};proto.setSlotCollapseEmpty=function(gptSlot,config){var globalMode=FT.ads.config('collapseEmpty'),mode=config.collapseEmpty;if(mode===true||mode==='after'){gptSlot.setCollapseEmptyDiv(true);}else if(mode==='before'){gptSlot.setCollapseEmptyDiv(true,true);}else if(mode===false||mode==='never'){gptSlot.setCollapseEmptyDiv(false);}
return mode;};proto.setSlotTargeting=function(gptSlot,targetingObj){if(FT._ads.utils.isPlainObject(targetingObj)){var targetKey;for(targetKey in targetingObj){if(targetingObj.hasOwnProperty(targetKey)){gptSlot.setTargeting(targetKey,targetingObj[targetKey]);}}}};proto.init=function(){var context=this,responsive=FT.ads.config('responsive');FT._ads.utils.attach('//www.googletagservices.com/tag/js/gpt.js',true);this.setPageTargeting();if(FT.env&&(!FT._ads.utils.isFunction(FT.env.refreshCancelFilter)||!FT.env.refreshCancelFilter())){this.startRefresh();}
function onViewportChange(viewport){var slot,slotName,slots=FT.ads.slots,slotsForRefresh=[];for(slotName in slots){slot=slots[slotName];if(slot.gptSlot&&FT._ads.utils.isObject(slot.config.sizes)){if(slot.config.sizes[viewport]===false){slot.collapse();}else{if(!slot.isDisplayed){slot.isDisplayed=true;googletag.display(slot.gptSlot.getSlotId().getDomId());}else{slotsForRefresh.push(slot.gptSlot);}
slot.uncollapse();}}}
if(!!slotsForRefresh.length){context.refresh(slotsForRefresh);}}
if(FT._ads.utils.isObject(responsive)){this.responsive=FT._ads.utils.responsive(responsive,onViewportChange);}
this.setPageCollapseEmpty();googletag.cmd.push(function(){context.enableVideo();context.enableCompanions();googletag.pubads().enableAsyncRendering();googletag.pubads().addEventListener('slotRenderEnded',function(event){if(FT._ads.utils.isFunction(FT.ads.renderEnded)){var gptSlotId=event.slot.getSlotId(),domId=gptSlotId.getDomId().split('-'),iframeId='google_ads_iframe_'+gptSlotId.getId();event.iframe=document.getElementById(iframeId);event.name=domId[0];event.slotType=domId[1];event.slot=FT.ads.slots[name];FT.ads.renderEnded(event);}});googletag.enableServices();});return this;};FT._ads.utils.extend(FT.ads,{gpt:new GPT()});}(window,document));
(function(win,doc,undefined){"use strict";FT.ads.version={artifactVersion:"1.0.49",buildLifeId:"224946",buildLifeDate:"2014-09-01",gitRev:"98ba8",toString:function(){return" version: "+this.artifactVersion+" Build life id: "+this.buildLifeId+" Build date: "+this.buildLifeDate+" git revision: "+this.gitRev;}};}(window,document));
FT=FT||{};FT.HTMLAds=function(){this.HTMLAdData={'urlStem':'http://media.ft.com/adimages/banner/','injectionParentDiv':'banlb','injectionLegacyParentDiv':'ad-placeholder-banlb','injectionDiv':'corppop_overlay','injectionClass':'corppop_single_occurence','timeOutCookieName':'FT_AM','timeOutCookieVal':'Check','timeOutCookieLife':'21600000','urlStemClassicAMO':'http://media.ft.com/m/registration.ft.com/corporate/ns/amo/'};};FT.HTMLAds.prototype.buildAdURL=function(AYSC98,AYSC22,AYSC27,regex){var userType='anon/',fileName='',urlStemNewAMO;if((AYSC22.match(regex.cor[22]))||(AYSC22.match(regex.lv1[22]))||(AYSC22.match(regex.lv2[22]))){userType='subscribed/';}else if((AYSC22.match(regex.reg[22]))){userType='registered/';}
if(AYSC98===''||AYSC98.match(/PVT/)){AYSC27=AYSC27.toUpperCase();fileName=this.HTMLAdData.urlStem+AYSC27+'.js';}else{if((typeof FT.Properties.CORPORATE_AMO_BASE==="undefined")||(FT.Properties.CORPORATE_AMO_BASE==='')){urlStemNewAMO=this.HTMLAdData.urlStemClassicAMO;}else{urlStemNewAMO=FT.Properties.CORPORATE_AMO_BASE;}
fileName=urlStemNewAMO+userType+AYSC27;}
return fileName;};FT.HTMLAds.prototype.getHTMLAd=function(adType,inj,fileName){var CorppopDiv,CorppopDivName,corppopDivAgain,Script1;inj.style.display="block";CorppopDiv=document.getElementById(this.HTMLAdData.injectionDiv);CorppopDivName=this.HTMLAdData.injectionDiv;if(CorppopDiv===null){CorppopDiv=document.createElement("div");}
CorppopDiv.setAttribute("id",CorppopDivName);CorppopDiv.className=this.HTMLAdData.injectionClass;Script1=document.createElement('script');Script1.type='text/javascript';Script1.src=fileName;try{inj.appendChild(CorppopDiv);corppopDivAgain=document.getElementById(CorppopDivName);corppopDivAgain.appendChild(Script1);}catch(er2){clientAds.log(er2);}};FT.HTMLAds.prototype.isCorporateUser=function(AYSC97,AYSC98,AYSC22,AYSC27,regex){if(!AYSC27){return 0;}
if(AYSC98===''||(AYSC98.match(/PVT/))){if((AYSC22.match(/[<>]/))||(AYSC27.match(/[<>]/))||(AYSC27.match(/RES/))||(AYSC27.match(/PVT/))){return 0;}else if((!AYSC27.match(/[0-9A-Za-z]/))||(AYSC22.match(regex.cor[22]))||(AYSC22.match(regex.lv1[22]))||(AYSC22.match(regex.lv2[22]))){return 0;}}else if(AYSC98.match(/A/)&&!AYSC98.match(/IA/)){if((AYSC22.match(/[<>]/))||(AYSC27.match(/[<>]/))||(AYSC27.match(/RES/))||(AYSC27.match(/PVT/))){return 0;}else if((!AYSC27.match(/[0-9A-Za-z]/))){return 0;}else if(AYSC97.match(/c/)){return 0;}}else{return 0;}
return 1;};FT.HTMLAds.prototype.createCorppopCookie=function(timeoutTime){var name,val,date,expires;if(typeof timeoutTime==="undefined"){timeoutTime=this.HTMLAdData.timeOutCookieLife;}
name=this.HTMLAdData.timeOutCookieName;val=this.HTMLAdData.timeOutCookieVal;date=new Date();date.setTime(date.getTime()+(timeoutTime));FT._ads.utils.cookie(name,val,{expires:date});};FT.HTMLAds.prototype.timeOut=function(corppopTimeoutCookie,corppopOldTimeoutCookie){if(!corppopTimeoutCookie&&!corppopOldTimeoutCookie){return 1;}
return 0;};
(function(win,doc,undefined){"use strict";function switcher(){if(FT.HTMLAds){FT.corppop=new FT.HTMLAds();}
FT.ads.request=function(pos){if(pos==='corppop'){var AYSC_OK,TIME_OK,injectionPoint,inj,self,URL='',cookieConsentName='cookieconsent',cookieConsentAcceptanceValue='accepted',SubsLevelReplaceLookup={'edt':{'22':/^edit$/,'97':/^.*/},'int':{'22':/^Ftemp$/,'97':/^.*/},'cor':{'22':/^[N]*[PL][01][PL]*[1]*[PL][12][A-Za-z][A-Za-z]/,'97':/^c$/},'lv1':{'22':/^[PL]*[0]*[PL]1[A-Za-z][A-Za-z]/,'97':/^[^c]$/},'lv2':{'22':/^[N]*[PL]*[0]*[PL]2[A-Za-z][A-Za-z]/,'97':/^[^c]$/},'reg':{'22':/^[PL]0[A-Za-z][A-Za-z]/,'97':/^[^c]$/}},AYSC97=FT._ads.utils.getCookieParam("AYSC","97")||"",AYSC98=FT._ads.utils.getCookieParam("AYSC","98")||"",AYSC22=FT._ads.utils.getCookieParam("AYSC","22")||"",AYSC27=FT._ads.utils.getCookieParam("AYSC","27")||"",location=document.location.href;if(!location.match(/Authorised=false/)&&(FT._ads.utils.cookie(cookieConsentName)===cookieConsentAcceptanceValue)){if(!FT._ads.utils.isString(FT._ads.utils.cookie("AYSC"))){AYSC_OK=0;}else{AYSC_OK=FT.corppop.isCorporateUser(AYSC97,AYSC98,AYSC22,AYSC27,SubsLevelReplaceLookup);}
TIME_OK=FT.corppop.timeOut(FT._ads.utils.cookie("FT_AM"),FT._ads.utils.cookie("CorpPopTimeout"));injectionPoint=(FT.env.isLegacyAPI)?FT.corppop.HTMLAdData.injectionLegacyParentDiv:FT.corppop.HTMLAdData.injectionParentDiv;inj=document.getElementById(injectionPoint);if((AYSC_OK)&&(TIME_OK)&&(inj!==null)){URL=FT.corppop.buildAdURL(AYSC98,AYSC22,AYSC27,SubsLevelReplaceLookup);FT.corppop.getHTMLAd(pos,inj,URL);}}}
else{FT.ads.slots.initSlot.apply(FT.ads.slots,arguments);}};FT.ads.requestNewssubs=function(){};FT.ads.beginVideo=function(){return true;};var findNoAD=function(iframe,slotName,callback){if(iframe.attachEvent){iframe.attachEvent('onload',function(){try{var img,imgs=iframe.contentDocument.getElementsByTagName('img');imgs=FT._ads.utils.nodeListToArray(imgs);while(img=imgs.pop()){if(/ft-no-ad/.test(img.src)){callback(true,slotName);}else{callback(false,slotName);}}}catch(err){return false;}});}else{try{var img,imgs=Array.prototype.slice.call(iframe.contentDocument.getElementsByTagName('img'),0);while(img=imgs.pop()){if(/ft-no-ad/.test(img.src)){callback(true,slotName);}else{callback(false,slotName);}}}catch(err){return false;}
iframe.addEventListener('load',function(){try{var img,imgs=Array.prototype.slice.call(iframe.contentDocument.getElementsByTagName('img'),0);while(img=imgs.pop()){if(/ft-no-ad/.test(img.src)){callback(true,slotName);}else{callback(false,slotName);}}}catch(err){return false;}},false);}};FT.ads.renderEnded=function(event){if(event.slotType!=="oop"){if(event.isEmpty){event.slot.collapse();}else{findNoAD(event.iframe,event.name,function(isNoAd,name){if(isNoAd){FT.ads.slots[name].collapse();}else{FT.ads.slots[name].uncollapse();}});}}};var kruxId;if(FT.Properties.ENV==='p'){kruxId='IhGt1gAD';}else{kruxId='IgnVxTJW';}
FT.ads.config({collapseEmpty:'ft',metadata:true,audSci:true,krux:{limit:FT.env.kruxMaxSegs||false,id:kruxId,events:{dwell_time:{interval:5,id:'JCadw18P',total:600}}},socialReferrer:true,pageReferrer:true,cookieConsent:true,timestamp:true,version:true,refresh:{time:false,max:0,art:{time:false},ind:{time:900}}});if(/5887\.video$/.test(FT.ads.config('dfp_site'))){FT.ads.config('companions',true);FT.ads.config('video',true);}
if(!FT._ads.utils.isNonEmptyString(FT.ads.config('dfp_site'))){FT.ads.config('dfp_site','ftcom.5887.unclassified');}
FT.ads.gpt.init();FT.ads.cb.init();FT.ads.krux.init();}
switcher();}(window,document));