
FT.Share=FT.Share||{};FT.Share.twitterAccounts=(function(){var myself=this,twitterList;function update(){twitterList=(FT.storyTools&&FT.storyTools.twitterList)?FT.storyTools.twitterList:null;}
update();return{update:update,getList:function(section){if(twitterList){var articleSection=FT.$('#page-title .bc a').text()+section,matchSection=articleSection?articleSection.toLowerCase().replace(' ',''):"",relatedAccts,twitterAccount,j;for(j=0;j<twitterList.length;j++){twitterAccount=twitterList[j].name.toLowerCase().replace(' ','');if(matchSection.match(twitterAccount)){if(relatedAccts){relatedAccts=relatedAccts+","+twitterList[j].value;}else{relatedAccts=twitterList[j].value;}}}
if(!relatedAccts){relatedAccts=(FT.storyTools&&FT.storyTools.defaultTwitAct)?FT.storyTools.defaultTwitAct.name:"";}
return relatedAccts;}else{return"";}}};}());FT.Share=FT.Share||{};FT.Share.pageShareInfo=(function(){var myself=this;function update(){this.title=document.title.replace(/ - Financial Times$/,'');this.section=window.siteMapTerm?window.siteMapTerm.replace('Sections.',''):"";this.relatedAccts=FT.Share.twitterAccounts.getList(this.section);this.summary=(FT.storyTools&&FT.storyTools.storySummary)?FT.storyTools.storySummary.substring(0,255):"";this.originalUrl=document.URL;this.canonicalUrl=FT.$('link[rel=canonical]').attr('href')||this.originalUrl;}
update();return{update:update,title:this.title,section:this.section,relatedAccts:this.relatedAccts,summary:this.summary,originalUrl:this.originalUrl,canonicalUrl:this.canonicalUrl};}());FT.Share=FT.Share||{};FT.Share.bitlyService=(function(){var resultsByService={},defaultCallbacksByService={'shorten':{'success':function(bitlyData,responseData,textStatus,jqXHR){if(responseData&&responseData.status_code===200){resultsByService.shorten[bitlyData]=responseData.data.url;}else{resultsByService.shorten[bitlyData]=FT.Share.pageShareInfo.canonicalUrl;}},'error':function(bitlyData){resultsByService.shorten[bitlyData]=FT.Share.pageShareInfo.canonicalUrl;}}},servicesInProgress={},servicesCallbacks={};function getBitlyQueryStringByService(serviceName){return FT.Properties.Bitly.baseURl+serviceName+'?'+FT.$.param(FT.Properties.Bitly);}
function callBeforeSendCallbacks(serviceName,bitlyData){var i;if(servicesCallbacks[serviceName]&&servicesCallbacks[serviceName][bitlyData]){for(i=0;i<servicesCallbacks[serviceName][bitlyData].length;i++){if(typeof servicesCallbacks[serviceName][bitlyData][i].beforeSendCallback==='function'){servicesCallbacks[serviceName][bitlyData][i].beforeSendCallback();}}}}
function callCompleteCallbacks(serviceName,bitlyData,jqXHR){var i;if(servicesCallbacks[serviceName]&&servicesCallbacks[serviceName][bitlyData]){for(i=0;i<servicesCallbacks[serviceName][bitlyData].length;i++){if(typeof servicesCallbacks[serviceName][bitlyData][i].completeCallback==='function'){servicesCallbacks[serviceName][bitlyData][i].completeCallback(resultsByService[serviceName][bitlyData],jqXHR);}}}}
function getService(serviceName,bitlyData,beforeSendCallback,completeCallback){if(!resultsByService[serviceName]||!resultsByService[serviceName][bitlyData]){if(!resultsByService[serviceName]){resultsByService[serviceName]={};}
if(!servicesInProgress[serviceName]){servicesInProgress[serviceName]={};}
if(!servicesCallbacks[serviceName]){servicesCallbacks[serviceName]={};}
if(!servicesInProgress[serviceName]||(servicesInProgress[serviceName]&&!servicesInProgress[serviceName][bitlyData])){servicesCallbacks[serviceName][bitlyData]=[];servicesCallbacks[serviceName][bitlyData].push({'beforeSendCallback':beforeSendCallback,'completeCallback':completeCallback});FT.$.ajax({url:getBitlyQueryStringByService(serviceName),dataType:'jsonp',data:bitlyData,timeout:3000,async:true,beforeSend:function(){callBeforeSendCallbacks(serviceName,bitlyData);servicesInProgress[serviceName][bitlyData]=true;},success:function(responseData,textStatus,jqXHR){if(typeof defaultCallbacksByService[serviceName].success==='function'){defaultCallbacksByService[serviceName].success(bitlyData,responseData,textStatus,jqXHR);}
callCompleteCallbacks(serviceName,bitlyData,jqXHR);servicesInProgress[serviceName][bitlyData]=false;servicesCallbacks[serviceName][bitlyData].length=0;},error:function(jqXHR,textStatus,errorThrown){if(typeof defaultCallbacksByService[serviceName].error==='function'){defaultCallbacksByService[serviceName].error(bitlyData,jqXHR,textStatus,errorThrown);}
callCompleteCallbacks(serviceName,bitlyData,jqXHR);servicesInProgress[serviceName][bitlyData]=false;servicesCallbacks[serviceName][bitlyData].length=0;}});}else{if(typeof beforeSendCallback==='function'){beforeSendCallback();}
servicesCallbacks[serviceName][bitlyData].push({'completeCallback':completeCallback});}}else{if(typeof beforeSendCallback==='function'){beforeSendCallback();}
if(typeof completeCallback==='function'){completeCallback(resultsByService[serviceName][bitlyData]);}}}
return{shortenUrl:function(url,beforeSendCallback,completeCallback){getService('shorten','longUrl='+encodeURIComponent(url),beforeSendCallback,completeCallback);}};}());FT.Share=FT.Share||{};FT.Share.ShareItem=function(editorialShareItem,enableLabel){this.windowOpened=null;var hrefWithoutCanonicalChanged=editorialShareItem.link.replace('{title}',encodeURIComponent(FT.Share.pageShareInfo.title)).replace('{section}',encodeURIComponent(FT.Share.pageShareInfo.section)).replace('{summary}',FT.Share.pageShareInfo.summary).replace('{source}','Financial%20Times').replace('{originalUrl}',encodeURIComponent(FT.Share.pageShareInfo.originalUrl)).replace('{relatedAccts}',encodeURIComponent(FT.Share.pageShareInfo.relatedAccts)),popupWindowOptions='scrollbars=yes,resizable=yes,toolbar=no,location=yes,',linkHTML,listItemLinkHTML,myself=this;this.id=editorialShareItem.id;this.css=editorialShareItem.css;this.size=editorialShareItem.size;this.label=enableLabel!==false?editorialShareItem.label:'';this.href=hrefWithoutCanonicalChanged.replace('{canonicalurl}',encodeURIComponent(FT.Share.pageShareInfo.canonicalUrl)).replace('{url}',encodeURIComponent(FT.Share.pageShareInfo.canonicalUrl));linkHTML=FT.$('<a/>').attr('href',this.href).text(this.label).attr('si:link','social-media_'+this.id);listItemLinkHTML=FT.$('<li/>').addClass(this.id);function beforeSendCallback(){linkHTML.addClass('loading');listItemLinkHTML.addClass('loading');}
function completeCallback(shortUrl){linkHTML.removeClass('loading');listItemLinkHTML.removeClass('loading');myself.href=hrefWithoutCanonicalChanged.replace('{canonicalurl}',encodeURIComponent(shortUrl)).replace('{url}',encodeURIComponent(shortUrl));linkHTML.attr('href',myself.href);myself.windowOpened.location.href=myself.href;myself.windowOpened=null;if(!FT.$(document.body).attr('si:pageID')){FT.analytics.siteIntelligence.setPageId(pageUUID);}
FT.analytics.siteIntelligence.trackExternalLink(linkHTML[0],function(){});}
linkHTML.unbind().bind('click',function(e){e.preventDefault();if(!myself.windowOpened){if(myself.size){myself.windowOpened=window.open("",myself.id+'_share',popupWindowOptions+myself.size);}else{myself.windowOpened=window.open("",myself.id+'_share');}
FT.Share.bitlyService.shortenUrl(FT.Share.pageShareInfo.canonicalUrl,beforeSendCallback,completeCallback);}});listItemLinkHTML.append(linkHTML);if(this.css){listItemLinkHTML.attr('style',this.css);}
this.getRenderedLink=function(){return linkHTML;};this.getRenderedListItemLink=function(){return listItemLinkHTML;};};FT.Share=FT.Share||{};FT.Share.ShareManager=function(editorialShareList,enableLabel){var list=[];this.getShareItems=function(){var i,item;if(!editorialShareList||(editorialShareList&&editorialShareList.length===0)){return[];}
if(list.length===0){for(i=0;i<editorialShareList.length;i++){item=new FT.Share.ShareItem(editorialShareList[i],enableLabel);list.push(item);}}
return list;};};FT.analytics=FT.analytics||{};FT.analytics.modHoverCharts=(function($,$doc){"use strict";function wait_for_hover_render(callback){if(typeof callback==="undefined"){callback=function(){};}
var interval;interval=setInterval(function(){if($(".WSODHoverPopupInner div.contains").length>0){clearInterval(interval);callback();}},100);setTimeout(function(){clearInterval(interval);},3000);}
function sendTrackingTag(symbol){FT.analytics.siteIntelligence.sendAdditionalTracer("/hover","symbol="+symbol);}
function addEventListeners(){$('a[data-hover-chart]').on('mouseover.analyticsModHoverCharts',function(){var symbol=$(this).data('hover-chart');wait_for_hover_render(function(){sendTrackingTag(symbol);});});}
function destroy(){$doc.off('.analyticsModHoverCharts');}
function init(){destroy();addEventListeners();}
return{init:init,destroy:destroy};}(FT.$,FT.$doc));FT.render.articleReprintRepublish=(function($){var
ReprintForm,ReprintPopup,containerClass='reprintPopup',eventNamespace=".ReprintPopup",$ReprintButton=$('.reprintButton a'),$ReprintForm;var ReprintFormValidator={_fields:[],add:function($fields,validator,onErrorCallback,onValidCallback){var self=this,args=Array.prototype.slice.call(arguments,4);$fields.each(function(key,field){self._fields.push({field:$(field),args:args,validator:validator||function(){},onErrorCallback:onErrorCallback||function(){},onValidCallback:onValidCallback||function(){}});});},check:function(){var isValid=true;this._fields.map(function(input){isValid=isValid&&input.validator.apply(input.field,input.args);});return isValid;},validate:function(){var isValid=true;this._fields.map(function(input){if(!input.validator.apply(input.field,input.args)){isValid=false;input.onErrorCallback.call(input.field);}
else{input.onValidCallback.call(input.field);}});return isValid;}};var EmailValidator=function(){var re=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(this.val());},NotEmptyValidator=function(){var val=this.val().trim();return(val!="");},NameValidator=function(){var re=/^([a-zA-Z ]){2,30}$/;return re.test(this.val());},LengthValidator=function(length){var re=new RegExp("^(.){0,"+length+"}$");return re.test(this.val());},NumberValidator=function(){var isEmpty=this.val()=="";return isEmpty||/^\+?\d+$/.test(this.val());};ReprintForm={init:function(){$ReprintButton.one("click"+eventNamespace,this.load)
$ReprintButton.data("enhanced","false");},deInit:function(){$ReprintButton.off("click"+eventNamespace);$ReprintButton.data("enhanced","true");},load:function(e){e.preventDefault();$.get($ReprintButton.attr('href')).done(function(data){var
popupContent=($(data).find(".reprint-popup").length!=0)?$(data).find(".reprint-popup"):$(data).closest(".reprint-popup"),rp=new ReprintPopup({afterOpen:function(){var popup=this;$ReprintForm=$(".reprint-popup form");$("."+containerClass+" .close-button").live("click"+eventNamespace,function(){popup.close();});ReprintForm.initValidation();$("#send-reprint-republish").on("click"+eventNamespace,ReprintForm.submit);}});$ReprintButton.off("click"+eventNamespace);$ReprintButton.on("click"+eventNamespace,function(e){e.preventDefault();rp.open($ReprintButton,popupContent);});rp.open($ReprintButton,popupContent);});},initValidation:function(){var
$requiredFields=$ReprintForm.find(".rp-required"),$email=$('#rp-emailAddress'),$compName=$("#rp-companyName"),$orderCopiesTxt=$("#rp-orderCopiesTxt"),$rpCountry=$("#rp-country"),$redirect_emailComment=$("#rp-redirect_emailComment");function showErrorMessage(message){return function(){var $errorMessage=$("<span>"+message+"</span>").addClass("rp-invalid-content");this.next(".rp-invalid-content").remove().end().on("change",function(){$errorMessage.remove();}).after($errorMessage);};}
ReprintFormValidator.add($requiredFields,NotEmptyValidator,function(){var $field=this,$label=$field.siblings("label");$label.css('color',"red");$field.one("change",function(){$label.css('color','');});});ReprintFormValidator.add($email,EmailValidator,showErrorMessage("Invalid email address"));ReprintFormValidator.add($rpCountry,NameValidator,showErrorMessage("Invalid country"));ReprintFormValidator.add($compName,LengthValidator,showErrorMessage("Invalid length"),function(){},50);ReprintFormValidator.add($redirect_emailComment,LengthValidator,showErrorMessage("Message too long"),function(){},160);ReprintFormValidator.add($orderCopiesTxt,NumberValidator,showErrorMessage("Invalid number"));},getFieldValues:function(){var licenseArray=[],licenseList,formValues=$ReprintForm.serializeArray();jQuery.each(formValues,function(k,v){if(v.name=="license"||v.name=="other"){licenseArray.push(v.value);}});licenseList=licenseArray.join(", ");formValues.push({name:"licenseList",value:licenseList});return formValues;},submit:function(e){var formValues=ReprintForm.getFieldValues();e.preventDefault();if(ReprintForm.validate()){var
$reprintPopupResponse,$cont=$("."+containerClass+" .popup-body");$cont.html("<iframe id='rp-reprintPopupResponse' src='http://presscuttings.ft.com/presscuttings/sendOrderReprintLink.htm?"
+$.param(formValues)+"'></iframe> ");$cont.prepend($('<span class="popup-loader" />'));$cont.append($('<div class="form-buttons"><a href="#" class="ft-button ft-button-medium ft-button-negative close-button">Close</a></div>'));$reprintPopupResponse=$("#rp-reprintPopupResponse");$reprintPopupResponse.hide();$reprintPopupResponse.on("load",function(){$reprintPopupResponse.show().siblings(".popup-loader").hide();});ReprintForm.deInit();ReprintForm.init();}},validate:function(){return ReprintFormValidator.validate();}};ReprintPopup=function(settings){var
defaults={isModal:false,animationSpeed:200,backOpacity:0.7,activeClass:"reprintPopup-active",backClass:'reprintPopup-back',contentClass:'reprintPopup-content',markup:'<div class="reprintPopup-cont"><div class="reprintPopup-content"/></div>',closeContent:'<a class="reprintPopup-close" href="#">&times;</a>',content:null,beforeOpen:function(){},afterOpen:function(){},beforeClose:function(){},afterClose:function(){},error:function(){}},self=this,$self,$popupContent,$back,$closeButton;self.settings=$.extend(true,{},defaults,settings);self.open=function(el,content){content=(content===undefined)?self.settings.content:content;if(content===null){return false;}
if(el!==undefined){self.$el=$(el);if(self.settings.activeClass){self.$el.addClass(self.settings.activeClass);}}
if($back===undefined){$back=$('<div class="'+self.settings.backClass+'"/>').appendTo($("body")).css("opacity",0).animate({opacity:self.settings.backOpacity},self.settings.animationSpeed);if(!self.settings.isModal){$back.one('click'+eventNamespace,function(){self.close();});}}
self.settings.beforeOpen.call(self);_showContent.call(self,content);return self;};function _showContent(content){if($popupContent===undefined){$popupContent=$('<div class="'+containerClass+'"/>');$self=$(self.settings.markup).appendTo($popupContent);$closeButton=$(self.settings.closeContent).one('click'+eventNamespace,function(e){e.preventDefault();self.close();}).appendTo($popupContent);$(window).on("resize"+eventNamespace,self.positionPopup);$popupContent.appendTo($('body')).css('opacity',0);}
if($self.hasClass(self.settings.contentClass)){$self.html(content);}
else{$self.find('.'+self.settings.contentClass).html(content);}
_showPopup.call(self,$popupContent);}
function _showPopup($popup){if($popup!==undefined){self.positionPopup();$popup.animate({opacity:1},self.animationSpeed,function(){self.settings.afterOpen.call(self);});}}
function _hidePopup($popup){if($popup!==undefined){$popup.animate({opacity:1},self.animationSpeed);}}
function _cleanUp(){$back.add($popupContent).remove();$popupContent=$back=undefined;$(window).off('resize'+eventNamespace);}
function _getCenter(){var pW=$popupContent.children().outerWidth(true),pH=$popupContent.children().outerHeight(true),wW=document.documentElement.clientWidth,wH=document.documentElement.clientHeight;return{top:wH*0.5-pH*0.5,left:wW*0.5-pW*0.5};};self.close=function(){self.settings.beforeClose.call(self);_hidePopup.call(self,$popupContent);if($back!==undefined){$back.animate({opacity:0},self.settings.animationSpeed,function(){_cleanUp();});}
return self;};self.positionPopup=function(){$popupContent.css(_getCenter());var pH=$popupContent.children().outerHeight(true),wH=document.documentElement.clientHeight;if(pH>wH){$popupContent.css({top:100,position:"absolute"});}
else{$popupContent.css({position:"fixed"});}
$back.css({height:document.documentElement.clientHeight});return self;};};return{varsion:"1.0",init:function(){ReprintForm.init();}};})(FT.$);FT.render.ArticleSlideshow=function(el){var currentSlide,slideList=el.find(".carousel-collection"),slideListItems=slideList.find(".carousel-item"),totalSlides=slideListItems.size(),carousel,featureGroup=String(el.data('feature-group')),myself=this;function init(){carousel=new FT.render.Carousel(el,{itemsPerView:1,onChange:function(g){myself.setCurrentSlide(g);}});showInitialSlide();bindKeyEvents();bindCustomEvents();}
function isValidSlide(n){return(typeof n==="number"&&(n>=0&&n<totalSlides));}
function showInitialSlide(){var hashSlide=parseInt(document.location.hash.replace(/#slide/,""),10),initialSlide,initialSlideEl;if(isValidSlide(hashSlide)){initialSlide=hashSlide;}else{initialSlideEl=slideListItems.filter(function(){return FT.$(this).children("noscript").size()===0;});initialSlide=slideListItems.index(initialSlideEl);}
myself.setCurrentSlide(initialSlide||0);}
function preloadSlide(n){if(!isValidSlide(n)){return;}
var imgDataEl=slideListItems.eq(n).find("noscript"),imgEl;if(imgDataEl.size()){slideListItems.eq(n).addClass("slideshow-loading");imgEl=FT.$("<img />",{src:imgDataEl.data("src"),alt:imgDataEl.data("alt"),width:imgDataEl.data("width"),height:imgDataEl.data("height")}).load(function(){if(slideListItems){slideListItems.eq(n).removeClass("slideshow-loading");}});imgDataEl.remove();slideListItems.eq(n).prepend(imgEl);}}
function bindKeyEvents(){FT.$(document.body).on("keydown."+featureGroup,function(e){if(e.which===37){myself.goToPrevious();}
if(e.which===39){myself.goToNext();}});}
function bindCustomEvents(){FT.customEvents.listen(featureGroup,function(data){if(data.featureType==="slideshowThumbnails"){myself.setCurrentSlide(data.selected);}});}
this.goToNext=function(){myself.setCurrentSlide(currentSlide+1);};this.goToPrevious=function(){myself.setCurrentSlide(currentSlide-1);};this.setCurrentSlide=function(n){if(isValidSlide(n)&&n!==currentSlide){currentSlide=n;preloadSlide(currentSlide);carousel.setCurrentItem(currentSlide);preloadSlide(currentSlide+1);preloadSlide(currentSlide-1);document.location.hash="slide"+n;FT.customEvents.trigger(featureGroup,{featureType:'slideshow',selectedSlide:currentSlide});FT.analytics.siteIntelligence.sendAdditionalTracer("/eventonpage","type=slideshow&data=slide"+n);}};this.getCurrentSlide=function(){return currentSlide;};this.destroy=function(){carousel.destroy();FT.customEvents.unlisten(featureGroup);FT.$(document.body).off("keydown."+featureGroup);slideListItems=null;totalSlides=null;};init();};FT.render.expandablePicture=null;FT.render.expandablePicturePopupWindow=null;FT.Render.ExpandablePicture=function(el){this.el=FT.$(el);this.addEvents();};FT.Render.ExpandablePicture.prototype.addEvents=function(){this.el.find('a').click(function(eventData){var href=FT.$(this).attr('href'),att=FT.lib.hashQueryString(href);att.url=href.split('?')[0];att.desc=att.desc||'';FT.Render.ExpandablePictureWinPop(att);eventData.preventDefault();eventData.stopImmediatePropagation();});};FT.Render.ExpandablePictureActivate=function(){if(FT.$('#expandableimage')){FT.render.expandablePicture=new FT.Render.ExpandablePicture('div.expandable-image');}};FT.Render.ExpandablePictureWinPop=function(att){var outerWidth=parseInt(att.width,10)+32,outerHeight=parseInt(att.height,10)+18;att.desc=att.desc||"";att.title=att.title||"";if(FT.render.expandablePicturePopupWindow){FT.render.expandablePicturePopupWindow.close();FT.render.expandablePicturePopupWindow=null;}
FT.render.expandablePicturePopupWindow=window.open(FT.Properties.HTML_BASE+"expandable-picture.htm?d="+(FT.comments.type==="inferno"?"true":"false"),"expandablePicture","width="+outerWidth+",height="+outerHeight+",toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=1,resizable=1");if(FT.render.expandablePicturePopupWindow){FT.$(document).one('popupReady.expandablePicture',function(){FT.render.expandablePicturePopupWindow.document.title=decodeURIComponent(att.title);FT.$(FT.render.expandablePicturePopupWindow.document).find('body').html('<img src="'+att.url+'" alt="'+decodeURIComponent(att.desc).replace(/"/g,'&quot;')+'" />');});FT.render.expandablePicturePopupWindow.focus();}};FT.render.flashManagerSettings={requiredVersion:'9.0.0'};FT.render.flashManagerPopupWindow=null;FT.render.flashManagers=[];FT.Render.FlashManager=function(el){this.el=FT.$(el);this.init=function(){if(swfobject.hasFlashPlayerVersion(FT.render.flashManagerSettings.requiredVersion)){this.injectFlash();}else{this.handleOldFlash();}};this.handleOldFlash=function(){this.el.find('.flasherrors').removeClass('hidden');};this.injectFlash=function(){var href=this.el.find('a.flashlink').attr('href'),att=FT.lib.hashQueryString(href),parObj={wmode:"opaque"};att.data=href.split('?')[0];if(this.el.hasClass('popup')){this.el.find('a').click(function(eventData){FT.Render.FlashManagerWinPop(att);eventData.preventDefault();eventData.stopImmediatePropagation();});}else{swfobject.createSWF(att,parObj,this.el.find('div.flashcontent').find('a').attr('id'));}
this.el.find('div.flashcontent').removeClass('hidden');};this.init();};FT.Render.FlashManagerActivate=function(){FT.$('div.flashcomponent').each(function(){FT.render.flashManagers.push(new FT.Render.FlashManager(this));});};FT.Render.FlashManagerWinPop=function(att){var outerWidth=parseInt(att.width,10)+12,outerHeight=parseInt(att.height,10)+24;if(FT.render.flashManagerPopupWindow){FT.render.flashManagerPopupWindow.close();FT.render.flashManagerPopupWindow=null;}
FT.render.flashManagerPopupWindow=window.open(att.data,"FLASH_GALLERY","width="+outerWidth+",height="+outerHeight+",toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=0,resizable=0");if(FT.render.flashManagerPopupWindow){FT.render.flashManagerPopupWindow.focus();}};FT.InsideArticleShare=function(placeholder){var i,shareItem;this.placeholderList=FT.$(placeholder).find('ul');if(!this.placeholderList.length||!FT.storyTools||!FT.storyTools.shareList){return;}
this.shareManager=new FT.Share.ShareManager(FT.storyTools.shareList,false);this.shareList=this.shareManager.getShareItems();this.renderShareOptions=function(limit){if(!limit||limit>this.shareList.length){limit=this.shareList.length;}
for(i=0;i<limit;i++){shareItem=this.shareList[i].getRenderedListItemLink();if(i===limit-1){shareItem.addClass('last-child');}else if(i===0){shareItem.addClass('first-child');}
shareItem.appendTo(this.placeholderList);}};};FT.Render.Podcast=function(element,render){this.el=element;this.hasFlash=this.getHasFlash();this.data=this.getPodcastData();this.autoRender=(typeof render==="undefined")?true:render;FT.render.podcasts=FT.render.podcasts||{};if(!FT.render.podcasts[this.data.id]&&this.data){FT.render.podcasts[this.data.id]=this;}else{return;}
this.originalHTML=this.el.html();if(this.autoRender){if(FT.Render.Podcast.prototype.scriptLoaded){this.render();}else{this.loadDependencies(this.render);}}};FT.Render.Podcast.prototype.podhosterScriptURL="http://podcast.ft.com/embed.js";FT.Render.Podcast.prototype.podhosterStylesURL="http://podcast.ft.com/images/podhoster2.css";FT.Render.Podcast.prototype.scriptLoaded=false;FT.Render.Podcast.prototype.cssFile=null;FT.Render.Podcast.prototype.getHasFlash=function(){return(typeof swfobject==='object')?swfobject.hasFlashPlayerVersion('9.0.0'):true;};FT.Render.Podcast.prototype.getPodcastData=function(){var podcastFileAnchor=FT.$('a[rel]',this.el),podcastFileURL=podcastFileAnchor.attr("href"),urlParts,data;if(typeof this.el.attr("id")!=="string"||podcastFileAnchor.length===0||typeof podcastFileURL!=="string"){return false;}
urlParts=podcastFileURL.split('/');data={host:urlParts[2],sid:urlParts[4],pid:urlParts[5],enclosure:urlParts[6],id:this.el.attr("id"),podcastURL:podcastFileURL,title:FT.$('h4 a',this.el).text(),description:FT.$('.description',this.el).text(),share:podcastFileAnchor.attr("id")};return data;};FT.Render.Podcast.prototype.loadDependencies=function(scriptCallback){if(!FT.Render.Podcast.prototype.scriptLoaded){var myself=this;if(!FT.Render.Podcast.prototype.cssFile){FT.Render.Podcast.prototype.cssFile=FT.$('<link rel="stylesheet" type="text/css" href="'+FT.Render.Podcast.prototype.podhosterStylesURL+'"/>');FT.$('head').append(FT.Render.Podcast.prototype.cssFile);}
FT.$.getScript(FT.Render.Podcast.prototype.podhosterScriptURL,function(){FT.Render.Podcast.prototype.scriptLoaded=true;if(typeof scriptCallback==='function'){scriptCallback.call(myself);}});}};FT.Render.Podcast.prototype.render=function(){if(this.hasFlash&&typeof this.data==="object"&&typeof embedLink==="function"){embedLink(this.data.host,this.data.pid,this.data.sid,this.data.enclosure,this.data.title,this.data.description,this.data.id,this.data.share);this.el.removeClass("basic");}};FT.Render.Podcast.prototype.destroy=function(){this.el.html(this.originalHTML);delete FT.render.podcasts[this.data.id];delete this.data;};FT.Render.Promobox=function($el){FT.lib.sizeToOverflowedContent($el);};FT.Render.Pullquote=function(el){FT.lib.sizeToOverflowedContent(el);};FT.render.SlideshowThumbnails=function(el,initialSelection){var imageSet,carousel,featureGroup=String(el.data('feature-group')),myself=this;function init(){imageSet=new FT.render.ImageSet(el,el.find('li'),{onSelected:imageSelected});carousel=new FT.render.Carousel(el,{itemsPerView:getThumbnailsPerView()});FT.customEvents.listen(featureGroup,function(data){if(data.featureType==="slideshow"){myself.setCurrent(data.selectedSlide);}});if(typeof initialSelection==="number"){myself.setCurrent(initialSelection);}}
function getThumbnailsPerView(){return el.hasClass("thumbnails-wide")?7:4;}
function imageSelected(n){FT.customEvents.trigger(featureGroup,{featureType:"slideshowThumbnails",selected:n});}
this.setCurrent=function(n){imageSet.setSelected(n);carousel.setCurrentItem(n);};this.destroy=function(){imageSet.destroy();carousel.destroy();FT.customEvents.unlisten(featureGroup);};init();};FT.tweetypie=(function(){var maxCharacter=114;var tweetref=document.location.href;function init(){bindEvent();}
function getSelectionText(){var text='';if(window.getSelection){text=window.getSelection().toString().split('\n').join('');}else if(document.selection&&document.selection.type!=='Control'){text=document.selection.createRange().text.split('\n').join('');}
text=text.replace(/FT\.\$doc\.trigger.*?;/g,'');text=(text.length>maxCharacter)?text.substr(0,maxCharacter)+'...':text;return text;}
function clearSelection(){if(window.getSelection){if(window.getSelection().empty){window.getSelection().empty();}else if(window.getSelection().removeAllRanges){window.getSelection().removeAllRanges();}}else if(document.selection){document.selection.empty();}}
function launchPopup(text){var apiUrl='http://api.bitly.com/v3/shorten?login=ftshare&baseURl=http%3A%2F%2Fapi.bitly.com%2Fv3%2F&apiKey=R_2b14237f91d76519080dd5c0faf84cb7&longUrl='+encodeURIComponent(tweetref);$.ajax({'url':apiUrl,'dataType':'jsonp',success:function(response){var url=encodeURI(response.data.url);var location='https://twitter.com/intent/tweet?url='+url+'&text='+text+'&original_referer='+encodeURI(document.referrer)+'&related=fttheworld';window.open(location,'tweety_pie_pullquote','height=436,width=646');}});}
function showShareBox(prop){FT.$("#tweetText .pullquote").html('<span class="openQuote">&nbsp;</span>'+prop.selection);FT.$(".tweet-btn-container a").attr('data-text',prop.selection);FT.$("#tweetText").css({"top":prop.top+"px","left":prop.left+"px"}).show();}
function isInsideArticleComponent(target){var elemList=['.insideArticleShare','.story-package','.lastUpdated','.lastUpdated','.byline','.promobox','.ftbf-syndicationIndicator','iframe','.carousel'];return!target.closest(elemList.join(', ')).length;}
function bindEvent(){var selection='';var url='#';var overlay=FT.$("#tweetText");FT.$('.contentSection, h1').on({'mouseup':function(ev){var myTarget=FT.$(ev.target);if(isInsideArticleComponent(myTarget)){if((ev.which!=3)&&(myTarget.hasClass('fyre-comment-action-button')!==true)){if(myTarget.closest('article').length>0){tweetref=document.location.origin+document.location.pathname+'?hubRefSrc=permalink#lf_comment='+myTarget.closest('article').data('message-id');}else{tweetref=document.location.href;}
selection=getSelectionText();overlay.hide();var left=$('.contentSection').width();var top=ev.pageY-$('.contentSection').offset().top+overlay.height()+50;if(left===$("body").width()){left=left-overlay.width()-10;}
if(FT.$('#bannerAdvertContainer').length){top=top+FT.$('#bannerAdvertContainer').height();}
if(selection!==''){var boxProperties={'top':top,'left':left,'selection':selection,'url':url};showShareBox(boxProperties);}}}},'mousedown':function(ev){if(ev.which!=3){clearSelection();}}},'.standfirst, #storyContent, h1, .fyre-stream-content, #inferno-commentlist');FT.$(".twitterCloseOverlay").on('click',function(){overlay.hide();});overlay.on('click',function(ev){ev.stopPropagation();});FT.$('.pullquote').each(function(){var $this=FT.$(this);selection=$this.children('q').text();if(($this.parents('#tweetText').length===0)&&($this.children('.tweet-btn-container').length===0)){if(selection.length<(maxCharacter-3)){var html='<div class="tweet-btn-container"><a href="javascript:void(0)" class="tweet-btn" data-text="'+selection+'"><span class="quoteImg"></span><span class="label"><strong>Tweet</strong> this quote</span></a></div>';$this.append(html);}}});FT.$('.tweet-btn').on('click',function(ev){var $this=FT.$(this);if($this.parents('#tweetText').length===0){selection=$this.parents('.pullquote').children('q').text();ev.stopPropagation();}
launchPopup(selection);overlay.hide();});}
return{init:init};})();if(typeof FT.Tynt==="undefined"&&(!FT.render.page.isEditor()&&((FT&&FT.isPage&&FT.isPage.Story===1)||(pageUUID?pageUUID==="fe133a26-c948-11de-b551-00144feabdc0":true))&&(!FT.render.user.isInternal()))){var Tynt=Tynt||[];Tynt=(function(){var queueTimer,totalCharCount=0,t=[];t.push('cqolxGrS4r34rIadbiUt4I');t.i={"cc":"0","aw":"31","b":true,"ap":"High quality global journalism requires investment. Please share this article with others using the link below, do not cut &amp; paste the article. See our <a href='http://www.ft.com/servicestools/help/terms'>Ts&amp;Cs</a> and <a href='http://www.ft.com/servicestools/help/copyright'>Copyright Policy</a> for more detail. Email <a href='mailto:ftsales.support@ft.com'>ftsales.support@ft.com</a> to buy additional rights. ","t":true};FT.$.getScript("http://tcr.tynt.com/ti.js");function resetQueueTimer(){clearTimeout(queueTimer);queueTimer=null;}
function sendSITracer(){resetQueueTimer();FT.analytics.siteIntelligence.sendAdditionalTracer("/si/tynt_start","copied="+totalCharCount);totalCharCount=0;}
FT.$.aop.before({target:String,method:"indexOf"},function(){if(this.match(/.*tynt.com.*c=([^&]*)/)){var copyText=decodeURIComponent(RegExp.$1).replace(/ /g,"");totalCharCount+=copyText.length;resetQueueTimer();queueTimer=setTimeout(function(){sendSITracer();},1000);}});return t;}());}
FT.yahooFinanceReferrer=(function(){var myself=this;this.placeholder=FT.$('.fullstoryHeader');this.referredPlaceholderClass='fullstoryHeaderReferred';this.urlParameter={key:'referrer_id',value:'yahoofinance'};return{isReferred:function(){return FT.lib.getQueryStringParam(myself.urlParameter.key)===myself.urlParameter.value;},addLink:function(){myself.placeholder.append('<div class="referrerBacklink" id="yahooFinanceReferrerBacklink"><a title="Go to Yahoo! Finance" href="http://biz.yahoo.com/ft/"><img src="'+FT.Properties.IMG_BASE+'/article/yahoo-finance.png" alt="Yahoo Finance"></a></div>');myself.placeholder.addClass(myself.referredPlaceholderClass);if(FT.$('.source',myself.placeholder).length){myself.placeholder.addClass('referrerBacklinkWithSource');}}};}());FT.$(document).ready(function(){"use strict";var i,fullstoryBody;if(!FT.render.page.isEditor()){if(FT.$('#ft-story-tools-top').length){FT.render.storyToolsTop=new FT.StoryTools('#ft-story-tools-top');}
if(FT.$('#ft-story-tools-bottom').length){FT.render.storyToolsBottom=new FT.StoryTools('#ft-story-tools-bottom');}
if(FT.$('.insideArticleShare').length){FT.render.insideArticleShares=[];FT.$('.insideArticleShare').each(function(){FT.render.insideArticleShares.push(new FT.InsideArticleShare(FT.$(this)));});for(i=0;i<FT.render.insideArticleShares.length;i=i+1){if(FT.render.insideArticleShares[i]&&typeof FT.render.insideArticleShares[i].renderShareOptions==='function'){FT.render.insideArticleShares[i].renderShareOptions(4);}}}
if(FT.isPage.Story&&FT.yahooFinanceReferrer.isReferred()){FT.yahooFinanceReferrer.addLink();}
FT.$.ajax({url:"http://apis.markets.ft.com/widgets/Factory/Script?params=[{%22Id%22:%22Mouse%20Over%20Chart%20Module%22}]",dataType:"script",cache:true,success:function(){FT.analytics.modHoverCharts.init();}});if(!FT.render.page.isPreview()){FT.tweetypie.init();}}
fullstoryBody=FT.$("div.fullstoryBody");if(fullstoryBody.length>0){FT.render.fullstoryBodyObjs=[];fullstoryBody.find("div.podcast").each(function(){FT.render.fullstoryBodyObjs.push(new FT.Render.Podcast(FT.$(this)));});fullstoryBody.find("div.pullquote").each(function(){FT.render.fullstoryBodyObjs.push(new FT.Render.Pullquote(FT.$(this)));});fullstoryBody.find("div.promobox").each(function(){FT.render.fullstoryBodyObjs.push(new FT.Render.Promobox(FT.$(this)));});fullstoryBody.find(".slideshow").each(function(){var slideshowEl=FT.$(this),slideshow=new FT.render.ArticleSlideshow(slideshowEl),thumbnailEl=slideshowEl.next(".thumbnail-carousel");FT.render.fullstoryBodyObjs.push(slideshow);if(thumbnailEl.size()){FT.render.fullstoryBodyObjs.push(new FT.render.SlideshowThumbnails(thumbnailEl,slideshow.getCurrentSlide()));}});FT.Render.FlashManagerActivate();FT.Render.ExpandablePictureActivate();}
FT.render.articleReprintRepublish.init();});