######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 12 23:50:51 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h
SOURCES += imageviewer.cpp main.cpp
