######################################################################
# Automatically generated by qmake (3.0) Wed Oct 15 23:18:48 2014
######################################################################

TEMPLATE = app
TARGET = show-image
INCLUDEPATH += .

QT += widgets printsupport

CONFIG += mobility

# Input
HEADERS += imageviewer.h
SOURCES += imageviewer.cpp main.cpp
